algunos arreglos

diff --git a/AFRARECI b/AFRARECI
--- a/AFRARECI
+++ b/AFRARECI
@@ -41,14 +41,25 @@ function verificar_aniomesdia(){
 	#ANIOMESDIA debe ser una fecha valida
 	#ANIOMESDIA debe ser a lo sumo de un año de antiguedad
 	#ANIOMESDIA debe ser menor o igual a la fecha del día.
-	local fecha_file=`echo ${1##*/} | sed 's/^\(.*\)_\([1-2][0-9][0-9][0-9]\)\([0-1][0-9]\)\([0-3][0-9]\)/g'`
+	local fecha_file=`echo ${1##*/} | sed 's/^\(.*\)_\([1-2][0-9][0-9][0-9]\)\([0-1][0-9]\)\([0-3][0-9]\)/\2\3\4/g'`
 	local fecha_desde=`date +%Y%m%d -d "1 year ago"` #en osx no anda pero en ubuntu si..
 	local fecha_actual=`date +%Y%m%d`
+
+	#verifico si es una fecha valida
+	if ! date -d "${fecha_file:6:4}-${fecha_file:0:2}-${fecha_file:3:2}";
+		then 
+		log_info "Fecha invalida ${1##*/} - Fecha de archivo tiene valores invalidos"
+		rechazar-archivo $1
+		return 1
+	fi
+
 	#verifico los rangos
 	if ! verificar_fecha "$fecha_file" "$fecha_desde" "$fecha_actual" ;
 	then
 		rechazar_archivo "$1"
+		return 1
 	fi
+	return 0
 }
 
 function verificar_fecha(){
@@ -58,11 +69,10 @@ function verificar_fecha(){
 		elif [ $1 -le $3 ]
 		then
 			log_info "Fecha invalida ${1##*/} - Fecha de archivo inferior a un anio"
-			return 1
 		else
 			log_info "Fecha invalida ${1##*/} - Fecha de archivo no puede ser superior a la actual."
-			return 1
 	fi
+	return 1
 }
 
 function rechazar_archivo(){
@@ -116,10 +126,8 @@ function novedades_pedientes(){
 			AFRAUMBR &
 			PID=$(get_pid AFRAUMBR)
 			log_info "AFRAUMBR corriendo bajo el no.: $PID"
-			return 0
 		else
 			log_info "Invocacion de AFRAUMBR propuesta para el siguiente ciclo"
-			return 0
 		fi
 	fi
 	return 0
@@ -149,21 +157,21 @@ function procesar_novedades(){
 		do
 			#1) Verificar si es tipo texto
 			if verificar_tipo "$NOVEDIR/$file" ;
-				then
-					#2) Verificar que el formato del nombre del archivo sea correcto
-					#FORMATO CORRECTO: <cod_central>_<aniomesdia>
-					if verificar_formato "$NOVEDIR/$file" ; then
-						#3) Validar nombre de los archivos
-							#cod_central tiene que estar en el maestro de centrales
-							#aniomesdia tiene que ser fecha valida, maximo un año de antiguedad
-								#y tiene que ser menor que  o igual a la fecha actual
-						if verificar_cod_central "$NOVEDIR/$file" "$MAEDIR/CdC.mae" ; then
-							if verificar_aniomesdia "$NOVEDIR/$file" ; then
-								#4) Si es valido lo anterior se tienene que pasar a ACEPTADOS
-								aceptar_archivo "$NOVEDIR/$file"
-							fi
+			then
+				#2) Verificar que el formato del nombre del archivo sea correcto
+				#FORMATO CORRECTO: <cod_central>_<aniomesdia>
+				if verificar_formato "$NOVEDIR/$file" ; then
+					#3) Validar nombre de los archivos
+						#cod_central tiene que estar en el maestro de centrales
+						#aniomesdia tiene que ser fecha valida, maximo un año de antiguedad
+							#y tiene que ser menor que  o igual a la fecha actual
+					if verificar_cod_central "$NOVEDIR/$file" "$MAEDIR/CdC.mae" ; then
+						if verificar_aniomesdia "$NOVEDIR/$file" ; then
+							#4) Si es valido lo anterior se tienene que pasar a ACEPTADOS
+							aceptar_archivo "$NOVEDIR/$file"
 						fi
 					fi
+				fi
 			fi
 		done
 	fi
@@ -173,7 +181,7 @@ function procesar_novedades(){
 function verificar_formato(){
 	local errorCantidadCampos=""
 	local fecha=""
-	local control=`echo ${1##*/} | grep '^[A-Z,a-z]*_[0-9]{8}' &>/dev/null`
+	local control=`echo ${1##*/} | grep '^[A-Z,a-z]+_[0-9]{8}' &>/dev/null`
 
 	if [ "$control" == "" ];
 	 then
